config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: [:create]
  resource :users, only: [:create]
  resources :bathrooms do
    resources :comments, except: [:index, :show]
    resources :ratings, only: [:create]
  end

  root 'bathrooms#index'
  get 'register' => 'users#new'
  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'

end

app/models/bathroom.rb
class Bathroom < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  validates :location, presence: true
  validates :description, presence: true
  validates :user, presence: true

  def has_not_been_rated_by_user(user_id)
   !self.ratings.find_by(user_id: user_id)
  end

  def average_rating
    self.ratings.average(:number)
  end

  def self.search(search)
    where("location ILIKE ?", "%#{search}%")
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :bathroom
  belongs_to :user
  validates :text, presence: true
  validates :user, presence: true
  validates :bathroom, presence: true
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :bathroom
  validates_inclusion_of :number , :in => 0..10
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bathrooms
  has_many :comments
  has_many :ratings
  validates :username, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user, :logged_in?

  def current_user
    @user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/bathrooms_controller.rb
class BathroomsController < ApplicationController
  def index
    @bathrooms = Bathroom.all
    if params[:search]
      @bathrooms = Bathroom.search(params[:search]).order(created_at: :desc)
    end
  end

  def new
    @bathroom = Bathroom.new
  end

  def create
    if logged_in?
      @bathroom = Bathroom.new(bathroom_params)
      @bathroom.user_id = session[:user_id]
      if @bathroom.save
        redirect_to root_path
      else
        render :new
      end
    else
      redirect_to '/login'
    end
  end

  def show
    @bathroom = Bathroom.includes(:comments).find(params[:id])
  end

  def edit
    @bathroom = Bathroom.find(params[:id])
    unless @bathroom.user.id == session[:user_id]
      redirect_to "/login"
    end
  end

  def update
    @bathroom = Bathroom.find(params[:id])
    if logged_in? && @bathroom.user.id == current_user.id
      if @bathroom.update(bathroom_params)
        redirect_to bathroom_path(@bathroom)
      else
        render :new
      end
    else
      redirect_to '/login'
    end
  end

  def destroy
    @bathroom = Bathroom.find(params[:id])
    if logged_in? && @bathroom.user.id == current_user.id
      @bathroom.destroy
      redirect_to root_path
    else
      redirect_to '/login'
    end
  end

  private
  def bathroom_params
    params.require(:bathroom).permit(:location, :author_rating, :description, :picture_url)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    bathroom = Bathroom.find(params[:bathroom_id])
    @comment = bathroom.comments.new
    if request.xhr?
      render :new, layout: false
    end
  end

  def create
    if logged_in?
      bathroom = Bathroom.find(params[:bathroom_id])
      @comment = bathroom.comments.new(comment_params)
      @comment.user_id = session[:user_id]
      if @comment.save
        if request.xhr?
          render partial: "comment", layout: false, locals: {comment: @comment}
        else
          redirect_to(@comment.bathroom)
        end
      else
        render :new
      end
    else
      redirect_to '/login'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    unless @comment.user.id == session[:user_id]
      redirect_to "/login"
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if logged_in? && @comment.user.id == current_user.id
      if @comment.update(comment_params)
        redirect_to
      else
        render :new
      end
    else
      redirect_to '/login'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if logged_in? && @comment.user.id == current_user.id
      @comment.destroy
      redirect_to bathroom_path(@comment.bathroom)
    else
      redirect_to '/login'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    @bathroom = Bathroom.find(params[:bathroom_id])
    if logged_in?
      if @bathroom.has_not_been_rated_by_user(current_user.id)
        rating = @bathroom.ratings.new(number: params[:rating][:number])
        rating.user_id = session[:user_id]
        if rating.save
          redirect_to bathroom_path(@bathroom)
        else
          redirect_to bathroom_path(@bathroom)
        end
      else
        redirect_to bathroom_path(@bathroom)
      end
    else
      redirect_to '/login'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if request.xhr?
      render :new, layout: false
    end
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now.alert = 'Incorrect Username or password'
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    if request.xhr?
      render :new, layout: false
    end
  end

  def create
    @user = User.new(user_params)
    if (@user.save)
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bathrooms/_bathroom.html.erb
<p><%= link_to bathroom.location, bathroom_path(bathroom) %></p>
<p><%= bathroom.description %></p>

app/views/bathrooms/edit.html.erb
<h1 class="header">Edit Your Bathroom</h1>
<% if @bathroom.errors.any?  %>
  <ul>
  <% @bathroom.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
<%= form_for @bathroom do |f|%>
<div class="row">
  <div class="large-6 columns">
    <%= f.label :loaction %>
    <%= f.text_field :location %>
  </div>
  <div class="large-6 columns">
    <%= f.label :author_rating %>
    <%= f.text_field :author_rating %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
</div>
<div class="row">
  <div class="large-6 columns">
    <%= f.label :picture_url %>
    <%= f.text_field :picture_url %>
  </div>
  <div class="large-6 columns">
    <%= f.submit :class => "button create-post"%>
  </div>
</div>
<%end%>

app/views/bathrooms/index.html.erb
<div class="errors">
</div>
<h1 class="header">Welcome to Prime Porcelain</h1>
<h2 class="header">The leader in Bathroom referall</h2>
<%= link_to "Add a Bathroom", new_bathroom_path, :id => "link-header" %>
<div id="user-box">
</div>
<%= form_tag(bathrooms_path, :method => "get", id: "search-form") do %>
<div class = "row">
	<div class="large-6 columns">
		<%= text_field_tag :search, params[:search], placeholder: "Search Locations" %>
	</div>
	<div class="large-6 columns">
		<%= submit_tag "Search" , :class => "button"%>
	</div>
</div>
<% end %>
<div class="container">
	<%@bathrooms.each do |bathroom| %>
	<div class="bathroom">
	  <p><%= link_to bathroom.location, bathroom_path(bathroom) %></p>
	  <p><%= bathroom.description %></p>
	</div>
	<%end%>
</div>

app/views/bathrooms/new.html.erb
<h1 class="header">Post a new Bathroom</h1>
<% if @bathroom.errors.any?  %>
  <ul>
  <% @bathroom.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
<%= form_for @bathroom do |f|%>
<div class="row">
  <div class="large-6 columns">
    <%= f.label :loaction %>
    <%= f.text_field :location %>
  </div>
  <div class="large-6 columns">
    <%= f.label :author_rating %>
    <%= f.text_field :author_rating %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
</div>
<div class="row">
  <div class="large-6 columns">
    <%= f.label :picture_url %>
    <%= f.text_field :picture_url %>
  </div>
  <div class="large-6 columns">
    <%= f.submit :class => "button create-post"%>
  </div>
</div>
<%end%>

app/views/bathrooms/show.html.erb
<div class="errors">
</div>
<h1 class="header">Welcome to the Prime Porcelain page for <%= @bathroom.location %>'s Bathroom</h1>
<div class="bathroom-container">
<h3 class="header">Average rating: <%= @bathroom.average_rating %></h3>
<div class="link-container">
<%= link_to "Edit", edit_bathroom_path(@bathroom) , :class => "button link-header"%>
<%= link_to "Destroy", bathroom_path(@bathroom), method: :delete, :class => "button link-header"%>
<%= link_to "Add a Comment", new_bathroom_comment_path(bathroom_id: params[:id]), :class => "button link-header comment-new" %>
</div>
<p class="header">Posted By: <%= @bathroom.user.username %></p>
<p class="header">Location: <%= @bathroom.location %></p>
<p class="header">Author Rating: <%= @bathroom.author_rating %></p>
<p class="header">Description: <%= @bathroom.description %></p>
<img src="<%= @bathroom.picture_url %>" class="img"/>
<h1 class="header">Rate this bathroom</h1>
<%= form_for [@bathroom, @bathroom.ratings.new] do |f| %>
<div class="row">
	<div class="large-2 columns">
		<%= f.label "Rating" , :class => "num-label"%>
	</div>
	<div class="large-8 columns">
		<%= f.select :number, (0..10) %>
	</div>
	<div class="large-2 columns">
		<%= f.submit "Rate", :class => "button"%>
	</div>
</div>
<%end%>
</div>
<div class="comment-container">
</div>
<div class="comments">
<%if @bathroom.comments.any? %>
<% @bathroom.comments.reverse.each do |comment| %>
<div class="comment">
<p><%= comment.text %></p>
<p>By: <%= comment.user.username %></p>
<p><%= link_to "Edit" ,edit_bathroom_comment_path(bathroom_id: params[:id], id: comment.id) %></p>
</div>
<%end%>
<%end%>
</div>

app/views/comments/_comment.html.erb
<p><%= comment.text %></p>
<p>By: <%= comment.user.username %></p>
<p><%= link_to "Edit" ,edit_bathroom_comment_path(bathroom_id: comment.bathroom.id, id: comment.id) %></p>

app/views/comments/edit.html.erb
<h3 class="header">Edit Comment</h3>
<div class="new-comment">
<%= form_for [@comment.bathroom , @comment] do |f|%>
<div class="row">
<div class="large-4 columns">
  <%= f.label :text , :class => "num-label header"%>
  <%= f.text_area :text %>
</div>
</div>
<div class="submit-comment">
  <%= f.submit "Add Comment" , :class => "button" %>
</div>
<%end%>
<button><%= link_to "Delete Comment", [@comment.bathroom, @comment], method: :delete, :class => "button delete-button", :id => "delete-button" %></button>
</div>

app/views/comments/new.html.erb
<h3 class="header">Make a new Comment</h3>
<div class="new-comment">
<%= form_for [@comment.bathroom , @comment] do |f|%>
<div class="row">
<div class="large-4 columns">
  <%= f.label :text , :class => "num-label header"%>
  <%= f.text_area :text %>
</div>
</div>
<div class="submit-comment">
  <%= f.submit "Add Comment" , :class => "button" %>
</div>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Cinzel+Decorative' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav>
      <ul>
        <% if logged_in? %>
        <li><%= link_to "Logout", logout_path, :class => "button"%></li>
        <%else%>
        <li><%= link_to "Login", login_path, :class => "button login-button" %></li>
        <li><%= link_to "Register", register_path, :class => "button register-button" %></li>
        <%end%>
        <li><%= link_to "Home", root_path, :class => "button"%></li>
      </ul>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<h1 class="header">Sign Up!</h1>
<%= form_for @user do |f| %>
   <fieldset>
   	<div class="row">
   		<div class="large-6 columns">
		    <%= f.label :username %>
		    <%= f.text_field :username %>
		</div>
	</div>

	<div class="row">
		<div class="large-6 columns">
     		<%= f.label :password %>
     		<%= f.password_field :password %>
     	</div>
     	<div class="large-6 columns">
     		<%= f.label :password_confirmation %>
     		<%= f.password_field :password_confirmation %>
     	</div>
     </div>

     <div class="row">
     	<div class="large-6 columns">
     		<%= f.submit %>
     	</div>
     </div>

   </fieldset>
<% end %>